#! /bin/bash

: ${YT_DLP_DIR:=$PWD}
: ${YT_DLP_COOKIES:=}

echo "Using destination path: ${YT_DLP_DIR}"

if [[ ${YT_DLP_COOKIES} ]]; then
    cookies_volume="-v ${YT_DLP_COOKIES}:/cookies.txt:ro"
    cookies_option="--cookies /cookies.txt"
else
    cookies_volume=""
    cookies_option=""
fi

if [[ -x /usr/local/bin/yt-dlp ]]; then
    yt_dlp="/usr/local/bin/yt-dlp -P ${YT_DLP_DIR}"
elif [[ -x /usr/bin/yt-dlp ]]; then
    yt_dlp="/usr/bin/yt-dlp -P ${YT_DLP_DIR}"
else
    yt_dlp="docker run --rm --user $UID:$GID -v "$YT_DLP_DIR:/downloads" ${cookies_volume} jauderho/yt-dlp"
fi

${yt_dlp} ${cookies_option} "$@"
